import React from 'react';
import { Typography, Space, Card, Row, Col } from 'antd';
import { RobotOutlined, SafetyOutlined, ThunderboltOutlined } from '@ant-design/icons';

const { Title, Paragraph } = Typography;

const Hero = ({ titleText, descriptionText }) => {
  return (
    <div style={{ 
      background: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
      padding: '60px 0',
      marginBottom: '40px'
    }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 20px' }}>
        <Row gutter={[48, 32]} align="middle">
          <Col xs={24} lg={12}>
            <Space direction="vertical" size="large" style={{ width: '100%' }}>
              <div>
                <Title level={1} style={{ 
                  marginBottom: '20px',
                  background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  fontSize: '3rem',
                  fontWeight: 'bold'
                }}>
                  {titleText || 'Free AI Text Detector - Detect AI-Generated Content Instantly'}
                </Title>
                <Paragraph style={{ 
                  fontSize: '18px', 
                  color: '#666',
                  lineHeight: '1.6',
                  marginBottom: '30px'
                }}>
                  {descriptionText || 'Our advanced AI-powered text analysis tool distinguishes between human-written and AI-generated content with 99% accuracy. Get instant results, detailed insights, and confidence scores to verify content authenticity.'}
                </Paragraph>
              </div>
              
              <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <SafetyOutlined style={{ color: '#52c41a', fontSize: '20px' }} />
                  <span style={{ color: '#666' }}>99% Accuracy</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <ThunderboltOutlined style={{ color: '#faad14', fontSize: '20px' }} />
                  <span style={{ color: '#666' }}>Instant Results</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                  <RobotOutlined style={{ color: '#1890ff', fontSize: '20px' }} />
                  <span style={{ color: '#666' }}>AI-Powered</span>
                </div>
              </div>
            </Space>
          </Col>
          
          <Col xs={24} lg={12}>
            <Card 
              style={{ 
                borderRadius: '16px',
                boxShadow: '0 8px 32px rgba(0,0,0,0.1)',
                border: 'none',
                background: 'rgba(255,255,255,0.9)',
                backdropFilter: 'blur(10px)'
              }}
            >
              <div style={{ textAlign: 'center', padding: '20px' }}>
                <RobotOutlined style={{ 
                  fontSize: '80px', 
                  color: '#667eea',
                  marginBottom: '20px'
                }} />
                <Title level={3} style={{ color: '#333', marginBottom: '10px' }}>
                  How Our AI Text Detection Works
                </Title>
                <Paragraph style={{ color: '#666', fontSize: '16px' }}>
                  Our advanced machine learning model analyzes text patterns, language complexity, 
                  writing style, and linguistic features to accurately determine if content was generated by AI or written by humans.
                </Paragraph>
              </div>
            </Card>
          </Col>
        </Row>
      </div>
    </div>
  );
};

export default Hero;
