import React from 'react';
import { Card, Tag, Typography, Progress, Space, Divider } from 'antd';
import { RobotOutlined, UserOutlined, TrophyOutlined } from '@ant-design/icons';

const { Text, Title } = Typography;

const ResultDisplay = ({ result }) => {
  if (!result) return null;

  const confidence = result.confidence || 0;
  const isAI = result.isAI;
  
  const getConfidenceColor = (confidence) => {
    if (confidence >= 80) return '#52c41a';
    if (confidence >= 60) return '#faad14';
    return '#ff4d4f';
  };

  const getConfidenceStatus = (confidence) => {
    if (confidence >= 80) return 'success';
    if (confidence >= 60) return 'normal';
    return 'exception';
  };

  return (
    <Card 
      style={{ 
        marginTop: '20px',
        borderRadius: '16px',
        border: 'none',
        boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
        background: 'linear-gradient(135deg, #f8f9ff 0%, #ffffff 100%)',
        animation: 'fadeInUp 0.6s ease-out'
      }}
    >
      <div style={{ textAlign: 'center', marginBottom: '30px' }}>
        <div style={{ 
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: '80px',
          height: '80px',
          borderRadius: '50%',
          background: isAI ? 'linear-gradient(135deg, #ff6b6b, #ee5a52)' : 'linear-gradient(135deg, #4ecdc4, #44a08d)',
          marginBottom: '20px',
          boxShadow: '0 8px 25px rgba(0,0,0,0.15)'
        }}>
          {isAI ? (
            <RobotOutlined style={{ fontSize: '40px', color: '#fff' }} />
          ) : (
            <UserOutlined style={{ fontSize: '40px', color: '#fff' }} />
          )}
        </div>
        
        <Title level={3} style={{ 
          margin: '0 0 10px 0',
          color: isAI ? '#ff4d4f' : '#52c41a'
        }}>
          {isAI ? 'AI Generated' : 'Human Written'}
        </Title>
        
        <Text style={{ color: '#666', fontSize: '16px' }}>
          {isAI 
            ? 'This text appears to be generated by artificial intelligence'
            : 'This text appears to be written by a human'
          }
        </Text>
      </div>

      <Divider />

      <Space direction="vertical" size="large" style={{ width: '100%' }}>
        {/* Confidence Score */}
        <div>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
            <Text strong style={{ fontSize: '16px' }}>Confidence Score</Text>
            <Tag 
              color={getConfidenceColor(confidence)}
              style={{ 
                fontSize: '14px',
                padding: '4px 12px',
                borderRadius: '12px'
              }}
            >
              {confidence}%
            </Tag>
          </div>
          <Progress 
            percent={confidence} 
            status={getConfidenceStatus(confidence)}
            strokeColor={getConfidenceColor(confidence)}
            strokeWidth={8}
            showInfo={false}
            style={{ marginBottom: '20px' }}
          />
        </div>

        {/* Classification */}
        <div style={{ 
          display: 'flex', 
          justifyContent: 'space-between', 
          alignItems: 'center',
          padding: '16px',
          background: isAI ? 'rgba(255, 77, 79, 0.1)' : 'rgba(82, 196, 26, 0.1)',
          borderRadius: '12px',
          border: `2px solid ${isAI ? 'rgba(255, 77, 79, 0.2)' : 'rgba(82, 196, 26, 0.2)'}`
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            {isAI ? (
              <RobotOutlined style={{ fontSize: '24px', color: '#ff4d4f' }} />
            ) : (
              <UserOutlined style={{ fontSize: '24px', color: '#52c41a' }} />
            )}
            <div>
              <Text strong style={{ fontSize: '16px', display: 'block' }}>
                Classification
              </Text>
              <Text style={{ color: '#666' }}>
                {isAI ? 'AI Generated Content' : 'Human Written Content'}
              </Text>
            </div>
          </div>
          <Tag 
            color={isAI ? 'red' : 'green'}
            style={{ 
              fontSize: '14px',
              padding: '6px 16px',
              borderRadius: '16px',
              fontWeight: 'bold'
            }}
          >
            {isAI ? 'AI' : 'Human'}
          </Tag>
        </div>

        {/* Additional Details */}
        {result.details && (
          <div style={{ 
            padding: '16px',
            background: '#f8f9fa',
            borderRadius: '12px',
            border: '1px solid #e9ecef'
          }}>
            <Text strong style={{ fontSize: '16px', display: 'block', marginBottom: '8px' }}>
              Analysis Details
            </Text>
            <Text style={{ color: '#666', lineHeight: '1.6' }}>
              {result.details}
            </Text>
          </div>
        )}

        {/* Trust Indicator */}
        <div style={{ 
          display: 'flex', 
          alignItems: 'center', 
          justifyContent: 'center',
          gap: '8px',
          padding: '12px',
          background: 'rgba(24, 144, 255, 0.1)',
          borderRadius: '12px',
          border: '1px solid rgba(24, 144, 255, 0.2)'
        }}>
          <TrophyOutlined style={{ color: '#1890ff', fontSize: '18px' }} />
          <Text style={{ color: '#1890ff', fontSize: '14px' }}>
            Powered by advanced AI detection technology
          </Text>
        </div>
      </Space>
    </Card>
  );
};

export default ResultDisplay;
